# Default values for presto

image:
  repository: ahanaio/prestodb
  pullPolicy: IfNotPresent
  tag: ~

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080
  labels: {}
  annotations: {}

ingress:
  enabled: false
  labels: {}
  annotations: {}
  ingressClassName: ~
  tls: []
  host: presto.local
  path: /
  pathType: Prefix

serviceAccount:
  create: true
  labels: {}
  annotations: {}

# Common environment variables
env: []
envFrom: []

# Common volumes
volumes: []
volumeMounts: []

# Common extra and init containers
containers: []
initContainers: []

# Constrain all presto pods to specific nodes
nodeSelector: {}
tolerations: []
affinity: {}

# Security context by default
securityContext: {}

# Presto home directory
home: /opt/presto-server

# Deployment mode
# single - Minimal Presto deployment where single pod acts as Coordinator and Worker
# cluster - Standard Presto deployment with one Coordinator and multiple Workers
# ha-cluster - [Not supported yet] Highly available Presto deployment with multiple Resource Managers, Coordinators and Workers
mode: cluster

# Common node properties, see https://prestodb.io/docs/current/installation/deployment.html#node-properties
node:
  environment: development
  dataDir: /var/presto/data

# Common JVM options, see https://prestodb.io/docs/current/installation/deployment.html#jvm-config
jvm: |-
  -server
  -XX:+ExitOnOutOfMemoryError
  -Djdk.attach.allowAttachSelf=true

# Common configuration properties, see https://prestodb.io/docs/current/installation/deployment.html#config-properties
config: |-
  query.max-memory=1GB
  query.max-memory-per-node=512MB

# Common log-levels properties, see https://prestodb.io/docs/current/installation/deployment.html#log-levels
log: |-
  com.facebook.presto=INFO

coordinator:
  # Coordinator JVM options (overwrites common JVM options)
  jvm: ""
  # Command and arguments to launch coordinator
  command: ["sh", "-c", "$PRESTO_HOME/bin/launcher run"]
  args: ~
  # Additional coordinator environment variables
  env: []
  envFrom: []
  # Additional coordinator volumes
  volumes: []
  volumeMounts: []
  # Additional coordinator extra and init containers
  containers: []
  initContainers: []
  # Coordinator liveness and readiness probes
  livenessProbe:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1
  # Coordinator resource limits and requests
  resources: {}
  # Constrain coordinator pods to specific nodes (overwrites common constraints)
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # Coordinator security context (overwrites default security context)
  securityContext: {}

worker:
  replicas: 2
  # Worker JVM options (overwrites common JVM options)
  jvm: ""
  # Command and arguments to launch worker
  command: ["sh", "-c", "$PRESTO_HOME/bin/launcher run"]
  args: ~
  # Additional worker environment variables
  env: []
  envFrom: []
  # Additional worker volumes
  volumes: []
  volumeMounts: []
  # Additional worker extra and init containers
  containers: []
  initContainers: []
  # Worker liveness and readiness probes
  livenessProbe:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1
  # Worker resource limits and requests
  resources: {}
  # Constrain worker pods to specific nodes (overwrites common constraints)
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # Worker security context (overwrites default security context)
  securityContext: {}

catalog:
  jmx: |-
    connector.name=jmx
